#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
#  thymeleaf:
#    cache: false
#    prefix: classpath:templates/
#    suffix: .html
#    view-names: thymeleaf/*
server:
  port: 8003
#thymeleaf:
#  cache: false
#spring:
#  mvc:view.suffix=.jsp
#spring:thymeleaf.prefix=classpath:/templates/
#spring:thymeleaf.cache=false
#spring:thymeleaf.view-names=thymeleaf/*

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jpapractice # jpaparactice ? ???????
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update # ???? ?????? ????? ?????? ??
    properties:
      hibernate:
        format_sql: true # format? ??? sql ? ????
        show_sql: true # sql??? ?????? ? ????????

logging:
  level:
    org.hibernate.type.descriptor.sql: trace